<a href="https://colab.research.google.com/github/LismyThomas/Data-science/blob/main/numpy_matrix_op.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np 


In [3]:
x = np.array([1,2,3,4])

In [4]:
print(x)

[1 2 3 4]


In [5]:
print(type(x))

<class 'numpy.ndarray'>


In [6]:
print(x.shape) 

(4,)


In [9]:
y = np.array([[1,2],[3,4]])

In [10]:
print(y)
print(y.shape)

[[1 2]
 [3 4]]
(2, 2)


In [12]:
z = np.array([[1+0.j,2+5.j]])

In [13]:
print(z)
print(z.shape)

[[1.+0.j 2.+5.j]]
(1, 2)


In [15]:
a = np.zeros((2,3))

In [16]:
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [17]:
print(a.shape)

(2, 3)


In [18]:
b = np.ones((2,3),dtype=int)

In [19]:
print(b)

[[1 1 1]
 [1 1 1]]


In [20]:
d = np.eye(3)

In [21]:
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
e = np.arange(10)

In [25]:
print(e)

[0 1 2 3 4 5 6 7 8 9]


In [26]:
e = np.arange(12,21)

In [27]:
print(e)

[12 13 14 15 16 17 18 19 20]


In [28]:
e = np.arange(5,20,3)

In [29]:
print(e)

[ 5  8 11 14 17]


In [30]:
f = np.linspace(1,20,7)

In [31]:
print(f)

[ 1.          4.16666667  7.33333333 10.5        13.66666667 16.83333333
 20.        ]


In [32]:
g = np.random.random((3,4))

In [33]:
print(g)

[[0.77225796 0.76151763 0.79557875 0.94663774]
 [0.68654798 0.23150475 0.79843864 0.30956713]
 [0.29434016 0.7130379  0.83035714 0.7026117 ]]


In [34]:
h = np.random.random((3,4))

In [35]:
print(h.reshape(2,2,3))

[[[0.65372272 0.42094809 0.58983753]
  [0.69623763 0.91728889 0.05290839]]

 [[0.72429468 0.31395067 0.35035738]
  [0.75977503 0.81215278 0.79799336]]]


In [36]:
x = np.arange(12)
print(x)
print(x[4])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
4


In [37]:
print(x[-1])

11


In [38]:
x.resize(3,4)

In [40]:
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [41]:
print(x[-1,-1])

11


In [42]:
print(x[2][3])

11


In [43]:
y = np.arange(1,26)
print(y)
print(y[:3])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
[1 2 3]


In [44]:
print(y[10:])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]


In [45]:
print(y[10:15])

[11 12 13 14 15]


In [46]:
print(y[-5:])

[21 22 23 24 25]


In [47]:
print(y[3:-3])

[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]


In [48]:
print(y[::3])

[ 1  4  7 10 13 16 19 22 25]


In [49]:
print(y.reshape((5,5)))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [50]:
y = y.reshape((5,5))
print(y)
print(y[:5,:5])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [51]:
print(y[2:-1,1:-1])

[[12 13 14]
 [17 18 19]]


In [52]:
print(y[:,:-1])

[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]
 [16 17 18 19]
 [21 22 23 24]]


In [53]:
print(y[:,-1])

[ 5 10 15 20 25]


In [54]:
print(y[::,::2])

[[ 1  3  5]
 [ 6  8 10]
 [11 13 15]
 [16 18 20]
 [21 23 25]]


In [55]:
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [56]:
print(y[1::2,1::2])

[[ 7  9]
 [17 19]]


In [57]:
a = np.arange(1,6)
b = np.arange(6,11)
print(a+b)
print(a-b)
print(b-a)
print(a**2)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[5 5 5 5 5]
[ 1  4  9 16 25]


In [58]:
print(a>3)

[False False False  True  True]


In [59]:
a = np.arange(0,4).reshape((2,2))

In [60]:
b = np.eye(2)

In [61]:
print(a*b)

[[0. 0.]
 [0. 3.]]


In [62]:
print(np.dot(a,b))

[[0. 1.]
 [2. 3.]]


In [63]:
x = np.arange(1,10).reshape(3,3)

In [64]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [65]:
print(x.sum())

45


In [66]:
print(x.sum(axis=0))

[12 15 18]


In [67]:
print(x.sum(axis=1))

[ 6 15 24]


In [68]:
x = np.arange(1,19).reshape(3,3,2)

In [69]:
print(x.sum(axis=1))

[[ 9 12]
 [27 30]
 [45 48]]


In [70]:
x = np.arange(1,10).reshape(3,3)

In [71]:
print(x)
print(x.max())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9


In [72]:
print(x.max(axis=0))

[7 8 9]


In [73]:
print(x.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]
